development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: WARNING
  pool: 5
  timeout: 5000
  database: 'destination_metrics_development'
  username: <%= ENV.fetch('POSTGRESUSER', 'pguser') %>
  password: <%= ENV.fetch('POSTGRESPASS', 'pgpass') %>

test:
  <<: *default
  database: destination_metrics_test

production:
  <<: *default
